-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 16:09:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sealclass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sealclass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sealclass` DEFAULT CHARACTER SET utf8 ;
USE `sealclass` ;

-- -----------------------------------------------------
-- Table `sealclass`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_user` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'user id',
  `sid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'school id',
  `phone` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `portrait` VARCHAR(1024) CHARACTER SET 'utf8' NULL,
  `role` TINYINT NOT NULL COMMENT 'role: superadmin/1, admin/2, teacher/3, student/4',
  `password` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'password hash',
  `salt` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'password salt',
  `device_id` VARCHAR(128) CHARACTER SET 'utf8' NULL,
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_user_uid_UNIQUE` (`uid` ASC),
  INDEX `t_user_uid_index` (`uid` ASC),
  INDEX `t_user_sid_index` (`sid` ASC),
  INDEX `t_user_phone_index` (`phone` ASC),
  INDEX `t_user_role_index` (`role` ASC),
  UNIQUE INDEX `t_user_sid_phone_UNIQUE` (`sid` ASC, `phone` ASC),
  INDEX `t_user_device_id_index` (`device_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealclass`.`t_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_room` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'room id',
  `sid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'school id',
  `name` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `portrait` VARCHAR(1024) CHARACTER SET 'utf8' NULL,
  `display` VARCHAR(1024) CHARACTER SET 'utf8' NULL COMMENT 'current display: teacher, whiteboard, screen',
  `whiteboard_name_index` INT NULL,
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_room_rid_sid_UNIQUE` (`rid` ASC, `sid` ASC),
  INDEX `t_room_rid_index` (`rid` ASC),
  INDEX `t_room_sid_index` (`sid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealclass`.`t_room_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_room_member` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_room_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'room id',
  `sid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `uid` VARCHAR(64) NOT NULL COMMENT 'user id',
  `role` TINYINT NOT NULL COMMENT 'role: superadmin/1, admin/2, teacher/3, student/4',
  `camera` TINYINT NULL DEFAULT 1,
  `mic` TINYINT NULL DEFAULT 1,
  `join_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_room_member_rid_uid_idx` (`rid` ASC, `uid` ASC),
  INDEX `t_room_member_uid_index` (`uid` ASC),
  INDEX `t_room_member_rid_index` (`rid` ASC),
  INDEX `t_room_member_sid_index` (`sid` ASC),
  INDEX `t_room_member_role_index` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealclass`.`t_whiteboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_whiteboard` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_whiteboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL COMMENT 'room id',
  `sid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `wb_room` VARCHAR(64) CHARACTER SET 'utf8' NULL COMMENT 'whiteboard room',
  `wbid` VARCHAR(1024) CHARACTER SET 'utf8' NULL COMMENT 'displayer uri',
  `name` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `creator` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `pg_count` INT NULL COMMENT 'total page size',
  `cur_pg` INT NULL COMMENT 'current page',
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `t_whiteboard_rid_index` (`rid` ASC),
  INDEX `t_whiteboard_sid_index` (`sid` ASC),
  INDEX `t_whiteboard_wb_room_index` (`wb_room` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealclass`.`t_school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_school` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_school` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sid` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `portrait` VARCHAR(1024) CHARACTER SET 'utf8' NULL,
  `manager` VARCHAR(64) CHARACTER SET 'utf8' NULL COMMENT 'manager uid',
  `appkey` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `secret` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_school_sid_UNIQUE` (`sid` ASC),
  INDEX `t_school_sid_index` (`sid` ASC),
  INDEX `t_school_manager_index` (`manager` ASC),
  INDEX `t_school_appkey_index` (`appkey` ASC),
  UNIQUE INDEX `appkey_UNIQUE` (`appkey` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealclass`.`t_appversion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sealclass`.`t_appversion` ;

CREATE TABLE IF NOT EXISTS `sealclass`.`t_appversion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `platform` TINYINT NOT NULL COMMENT 'Android: 1, iOS: 2',
  `url` VARCHAR(1024) CHARACTER SET 'utf8' NOT NULL,
  `version` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `update_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `platform` (`platform` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
